sudo: required

services:
  - docker

script:
  - docker build -t elasticsearch -f Dockerfile .
  - CONT_ID=`docker run -d -p 9200:9200 elasticsearch`
  - sleep 30 
  - docker exec ${CONT_ID} tail /usr/share/java/elasticsearch/logs/elasticsearch.log
  - ./test.sh
