sudo: required

services:
  - docker

env:
  - PROMETHEUS_PLUGIN=true
  - PROMETHEUS_PLUGIN=false

script:
  - docker build --build-arg PROMETHEUS_PLUGIN=${PROMETHEUS_PLUGIN} -t elasticsearch -f Dockerfile .
  - CONT_ID=`docker run -d -p 9200:9200 elasticsearch`
  - sleep 30 
  - docker exec ${CONT_ID} tail /usr/share/java/elasticsearch/logs/elasticsearch.log
  - ./test.sh
