#sg_all_access:
#  cluster:
#    - '*'
#  indices:
#    '*':
#      '*':
#        - '*'

sg_role_prometheus:
  cluster:
    - cluster:monitor/nodes/stats
    - cluster:monitor/health

sg_role_foo:
  cluster:
    - cluster:monitor/health
