#<sg_role_name>:
#  cluster:
#    - '<permission>'
#  indices:
#    '<indexname or alias>':
#      '<type>':  
#        - '<permission>'
#      _dls_: '<querydsl query>'
#      _fls_:
#        - '<field>'
#        - '<field>'

# Allows everything
# but not changes to searchguard config/index
sg_all_access:
  cluster:
    - '*'
  indices:
    '*':
      '*':
        - '*'

sg_role_prometheus:
  cluster:
    - cluster:monitor/nodes/stats
#    - cluster:monitor/_prometheus/metrics

sg_role_foo:
  indices:
    - indices:admin/*
#  cluster:
#    - cluster:monitor/nodes/stats
